#!/usr/bin/env bash
set -euo pipefail

# wal2swaync — Génère ~/.config/swaync/style.css à partir de wal

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=pywal-common.sh
. "$SCRIPT_DIR/pywal-common.sh"

TARGET="$HOME/.config/swaync/style.css"
OVERRIDE="$HOME/.config/swaync/style.overrides.css"

if ! CACHE_FILE="$(pywal_locate_file "colors")"; then
    echo "[wal2swaync] Palette introuvable." >&2
    exit 1
fi

{
    echo "/* Generated by pywal16 on $(date) */"
    for i in $(seq 0 15); do
        hex=$(sed -n "$((i+1))p" "$CACHE_FILE")
        echo "@define-color color$i $hex;"
    done
    echo
    [[ -f "$OVERRIDE" ]] && cat "$OVERRIDE"
} > "$TARGET"
