--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sabi/Images/wallpapers/Smoking_girl.png"

-- Special
background="#190a19"
foreground="#c5c1c5"
cursor="#c5c1c5"

-- Colors
color0="#190a19"
color1="#B04E74"
color2="#DB576E"
color3="#3C6D8A"
color4="#6E4787"
color5="#614883"
color6="#955089"
color7="#c5c1c5"
color8="#6e596e"
color9="#B04E74"
color10="#DB576E"
color11="#3C6D8A"
color12="#6E4787"
color13="#614883"
color14="#955089"
color15="#c5c1c5"
