# Shell variables
# Generated by 'wal'
wallpaper="/home/sabi/Images/wallpapers/4.png"

# Special
background='#121e2c'
foreground='#c3c6ca'
cursor='#c3c6ca'

# Colors
color0='#121e2c'
color1='#3F6683'
color2='#565D81'
color3='#665B82'
color4='#4B6584'
color5='#6E6188'
color6='#A46786'
color7='#c3c6ca'
color8='#616b77'
color9='#3F6683'
color10='#565D81'
color11='#665B82'
color12='#4B6584'
color13='#6E6188'
color14='#A46786'
color15='#c3c6ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
