--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sabi/Images/wallpapers/4.png"

-- Special
background="#121e2c"
foreground="#c3c6ca"
cursor="#c3c6ca"

-- Colors
color0="#121e2c"
color1="#3F6683"
color2="#565D81"
color3="#665B82"
color4="#4B6584"
color5="#6E6188"
color6="#A46786"
color7="#c3c6ca"
color8="#616b77"
color9="#3F6683"
color10="#565D81"
color11="#665B82"
color12="#4B6584"
color13="#6E6188"
color14="#A46786"
color15="#c3c6ca"
