# Shell variables
# Generated by 'wal'
wallpaper="/home/sabi/Images/wallpapers/Smoking_girl.png"

# Special
background='#190a19'
foreground='#c5c1c5'
cursor='#c5c1c5'

# Colors
color0='#190a19'
color1='#B04E74'
color2='#DB576E'
color3='#3C6D8A'
color4='#6E4787'
color5='#614883'
color6='#955089'
color7='#c5c1c5'
color8='#6e596e'
color9='#B04E74'
color10='#DB576E'
color11='#3C6D8A'
color12='#6E4787'
color13='#614883'
color14='#955089'
color15='#c5c1c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
