#!/usr/bin/env bash
# wal2swaync — Génère ~/.config/swaync/style.css à partir de wal

CACHE="$HOME/.cache/wal/colors"
TGT="$HOME/.config/swaync/style.css"
OVERRIDE="$HOME/.config/swaync/style.overrides.css"

{
  echo "/* Generated by pywal16 on $(date) */"
  for i in $(seq 0 15); do
    hex=$(sed -n "$((i+1))p" "$CACHE")
    echo "@define-color color$i $hex;"
  done
  echo
  [ -f "$OVERRIDE" ] && cat "$OVERRIDE"
} > "$TGT" 